-- Motorcycle Comparison API - Kawasaki engine specifications, researched set
-- Generated by tools/import-kawasaki-engine-research.mjs. Do not edit by hand; edit the
-- generator and re-run it, or the next run will silently revert whatever was changed here.
--
-- WHAT THIS IS, AND WHAT IT IS NOT
-- The sibling brand seeds in this folder are scrapes: each figure was parsed out of one named page
-- for that exact model year. This one is not. It fills the engine block for 424 Kawasaki
-- model-years the FIPE snapshot created without one, and its figures were researched per engine
-- family - manufacturer specification sheets where those exist, press and road-test material where
-- they do not - and then applied to every model year that shares the family. That is a weaker claim
-- than the other files in this folder make, and it is recorded here because the difference is not
-- visible once the numbers are rows in a table.
--
-- Two columns deserve the warning most. top_speed_kph and fuel_consumption_l_100km are almost never
-- published by the manufacturer; they come from magazine testing, they vary with rider, load and
-- conditions, and they should be read as indicative. The bore, stroke, displacement, cylinder count
-- and compression figures are on much firmer ground: they are physical properties of the engine,
-- they are published, and the check below proves them against each other.
--
-- ORDERING
-- Flyway runs repeatable migrations in description order, and this import only gap-fills, so it has
-- to run after the FIPE seed that creates the rows it fills. "motorcycles kawasaki specs research
-- 2026 08" sorts after "motorcycles brazil fipe 2026 08" (k > b) and after
-- "motorcycles kawasaki specs 2026 08" ('2' < 'r'), which is the order this file needs: the scraped
-- Kawasaki seed is the better-sourced of the two, so it goes first and its values win.
--
-- GAP-FILL ONLY
-- Every write below is COALESCE(existing, imported), so a value already in the catalogue is never
-- overwritten - not by this file, and not on a re-run. This file also creates no motorcycles. All
-- 424 slugs were present in the catalogue when it was generated, and a slug that is
-- missing at run time is skipped rather than inserted, because a row built from an engine block
-- alone would have no brand, model or year worth serving.
--
-- CHECKS APPLIED AT GENERATION
-- Nothing here is estimated or interpolated. A field the research could not establish is NULL.
-- Beyond that, four guards ran, and each drops a value rather than the row:
--   geometry     bore, stroke, cylinders and displacement have one algebraic relation, so the
--                quartet checks itself. Deviation over 1% drops bore and stroke and keeps
--                displacement. (0 values dropped)
--   bounds       each figure must sit inside a physically plausible range and inside the CHECK
--                constraints in V1__initial_schema.sql. (0 dropped)
--   rpm order    peak torque must not sit above peak power in the rev range, which would mean a
--                swapped pair. (0 dropped)
--   width        a string must fit its column, or it fails inside Flyway rather than here.
--                (0 dropped)
--
-- ERRATA, APPLIED BEFORE THE CHECKS
--   Z 750: bore 63.4 -> 68.4 mm (63.4 gives 643 cc, not the 748 cc the row states)
--   Z 1000 (953 cc): bore/stroke 77.0 x 51.8 -> 77.2 x 50.9 mm (77.0 x 51.8 gives 965 cc)
--
-- VALUES DROPPED BY THE CHECKS
--   (none)
--
-- COVERAGE OF THE 424 ROWS
--   engine_type                420 of 424
--   displacement_cc            420 of 424
--   cylinders                  420 of 424
--   valves_per_cylinder        411 of 424
--   max_power_hp               383 of 424
--   max_power_rpm              364 of 424
--   max_torque_nm              379 of 424
--   max_torque_rpm             365 of 424
--   compression_ratio          416 of 424
--   bore_mm                    416 of 424
--   stroke_mm                  416 of 424
--   cooling_system             420 of 424
--   fuel_system                420 of 424
--   transmission_type          420 of 424
--   gears                      420 of 424
--   final_drive                420 of 424
--   top_speed_kph              320 of 424
--   fuel_consumption_l_100km   262 of 424
--   emission_standard          420 of 424

BEGIN;

CREATE TEMP TABLE tmp_kawasaki_engine_research (
    row_no                   INTEGER PRIMARY KEY,
    slug                     TEXT NOT NULL,
    engine_type              VARCHAR(80),
    displacement_cc          INTEGER,
    cylinders                INTEGER,
    valves_per_cylinder      INTEGER,
    max_power_hp             NUMERIC(6, 1),
    max_power_rpm            INTEGER,
    max_torque_nm            NUMERIC(6, 1),
    max_torque_rpm           INTEGER,
    compression_ratio        VARCHAR(20),
    bore_mm                  NUMERIC(6, 2),
    stroke_mm                NUMERIC(6, 2),
    cooling_system           VARCHAR(40),
    fuel_system              VARCHAR(120),
    transmission_type        VARCHAR(60),
    gears                    INTEGER,
    final_drive              VARCHAR(40),
    top_speed_kph            INTEGER,
    fuel_consumption_l_100km NUMERIC(5, 2),
    emission_standard        VARCHAR(30),
    motorcycle_id            BIGINT,
    engine_id                BIGINT
) ON COMMIT DROP;

INSERT INTO tmp_kawasaki_engine_research (
    row_no, slug, engine_type, displacement_cc, cylinders, valves_per_cylinder, max_power_hp, max_power_rpm, max_torque_nm, max_torque_rpm, compression_ratio, bore_mm, stroke_mm, cooling_system, fuel_system, transmission_type, gears, final_drive, top_speed_kph, fuel_consumption_l_100km, emission_standard
) VALUES
(1, 'kawasaki-avajet-100cc-classic-100cc-1997', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'kawasaki-concours14-1352cc-2012', 'Liquid-cooled, DOHC, 4-valve, in-line four, VVT', 1352, 4, 4, 156, 8800, 140, 6200, '10.7:1', 84, 61, 'liquid', 'DFI, four 40mm throttle bodies', 'manual', 6, 'shaft', NULL, NULL, 'Euro 3'),
(3, 'kawasaki-concours14-1352cc-2013', 'Liquid-cooled, DOHC, 4-valve, in-line four, VVT', 1352, 4, 4, 156, 8800, 140, 6200, '10.7:1', 84, 61, 'liquid', 'DFI, four 40mm throttle bodies', 'manual', 6, 'shaft', NULL, NULL, 'Euro 3'),
(4, 'kawasaki-eliminator-500-2025', '4-stroke', 451, 2, 4, 47.2, 10430, 39.3, 7510, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 5'),
(5, 'kawasaki-eliminator-500-2026', '4-stroke', 451, 2, 4, 47.2, 10430, 39.3, 7510, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 5'),
(6, 'kawasaki-eliminator-500-se-2025', '4-stroke', 451, 2, 4, 47.2, 10430, 39.3, 7510, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 5'),
(7, 'kawasaki-eliminator-500-se-2026', '4-stroke', 451, 2, 4, 47.2, 10430, 39.3, 7510, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 5'),
(8, 'kawasaki-er-6n-650cc-2012', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 72, 8500, 64, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(9, 'kawasaki-er-6n-650cc-2013', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 72, 8500, 64, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(10, 'kawasaki-er-6n-650cc-2014', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 72, 8500, 64, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(11, 'kawasaki-er-6n-650cc-2015', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 72, 8500, 64, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(12, 'kawasaki-er-6n-650cc-2017', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 72, 8500, 64, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(13, 'kawasaki-klx-110-2009', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(14, 'kawasaki-klx-110-2010', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(15, 'kawasaki-klx-110-2020', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(16, 'kawasaki-klx-110-2021', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(17, 'kawasaki-klx-110-2022', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(18, 'kawasaki-klx-110-2023', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(19, 'kawasaki-klx-110-2024', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(20, 'kawasaki-klx-110-2025', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(21, 'kawasaki-klx-110-monster-2009', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(22, 'kawasaki-klx-110-monster-2010', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(23, 'kawasaki-klx-110-monster-2011', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(24, 'kawasaki-klx-110r-2026', '4-stroke', 112, 1, 2, 7, NULL, 8.1, NULL, '9.5:1', 53, 50.6, 'air', 'Keihin carburetor (small-bore CV)', 'automatic', 4, 'chain', 80, NULL, 'Off-road'),
(25, 'kawasaki-klx-250-1994', '4-stroke', 249, 1, 4, 27, 8500, 25.5, 7500, '11.0:1', 72, 61.2, 'liquid', 'Keihin CVK34 carburetor', 'manual', 6, 'chain', 137, NULL, 'Off-road'),
(26, 'kawasaki-klx-250-1995', '4-stroke', 249, 1, 4, 27, 8500, 25.5, 7500, '11.0:1', 72, 61.2, 'liquid', 'Keihin CVK34 carburetor', 'manual', 6, 'chain', 137, NULL, 'Off-road'),
(27, 'kawasaki-klx-250-1996', '4-stroke', 249, 1, 4, 27, 8500, 25.5, 7500, '11.0:1', 72, 61.2, 'liquid', 'Keihin CVK34 carburetor', 'manual', 6, 'chain', 137, NULL, 'Off-road'),
(28, 'kawasaki-klx-300r-2025', '4-stroke', 292, 1, 4, NULL, NULL, NULL, NULL, '11.0:1', 78, 61.2, 'liquid', 'DFI, 34mm Keihin throttle body', 'manual', 6, 'chain', NULL, NULL, 'Off-road'),
(29, 'kawasaki-klx-300r-2026', '4-stroke', 292, 1, 4, NULL, NULL, NULL, NULL, '11.0:1', 78, 61.2, 'liquid', 'DFI, 34mm Keihin throttle body', 'manual', 6, 'chain', NULL, NULL, 'Off-road'),
(30, 'kawasaki-klx-450r-2015', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.0:1', 96, 62.1, 'liquid', 'Keihin EFI', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(31, 'kawasaki-klx-450r-2017', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.0:1', 96, 62.1, 'liquid', 'Keihin EFI', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(32, 'kawasaki-klx-450r-2018', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.0:1', 96, 62.1, 'liquid', 'Keihin EFI', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(33, 'kawasaki-klx-450r-2019', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.0:1', 96, 62.1, 'liquid', 'Keihin EFI', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(34, 'kawasaki-klx-450r-2020', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.0:1', 96, 62.1, 'liquid', 'Keihin EFI', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(35, 'kawasaki-klx-450r-2021', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.0:1', 96, 62.1, 'liquid', 'Keihin EFI', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(36, 'kawasaki-klx-450r-2022', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.0:1', 96, 62.1, 'liquid', 'Keihin EFI', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(37, 'kawasaki-klx-450r-2023', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.0:1', 96, 62.1, 'liquid', 'Keihin EFI', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(38, 'kawasaki-klx-450r-2024', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.0:1', 96, 62.1, 'liquid', 'Keihin EFI', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(39, 'kawasaki-klx-650-1994', '4-stroke', 651, 1, 4, 45, 6500, 52, 5000, '9.5:1', 100, 83, 'liquid', 'Keihin 40mm carburetor', 'manual', 5, 'chain', 160, NULL, 'Off-road'),
(40, 'kawasaki-klx-650-1995', '4-stroke', 651, 1, 4, 45, 6500, 52, 5000, '9.5:1', 100, 83, 'liquid', 'Keihin 40mm carburetor', 'manual', 5, 'chain', 160, NULL, 'Off-road'),
(41, 'kawasaki-klx-650-1996', '4-stroke', 651, 1, 4, 45, 6500, 52, 5000, '9.5:1', 100, 83, 'liquid', 'Keihin 40mm carburetor', 'manual', 5, 'chain', 160, NULL, 'Off-road'),
(42, 'kawasaki-kx-112-2025', '2-stroke', 112, 1, NULL, NULL, NULL, NULL, NULL, '9.9:1', 52.5, 51.6, 'liquid', 'Keihin 28mm carburetor', 'manual', 6, 'chain', NULL, NULL, 'Off-road'),
(43, 'kawasaki-kx-125-2001', '2-stroke', 125, 1, NULL, 40, NULL, 26.5, 2700, '10.6:1', 54, 54.5, 'liquid', 'Mikuni 34mm flat-slide carburetor', 'manual', 6, 'chain', 125, NULL, 'Off-road'),
(44, 'kawasaki-kx-125-2002', '2-stroke', 125, 1, NULL, 40, NULL, 26.5, 2700, '10.6:1', 54, 54.5, 'liquid', 'Mikuni 34mm flat-slide carburetor', 'manual', 6, 'chain', 125, NULL, 'Off-road'),
(45, 'kawasaki-kx-125-2003', '2-stroke', 125, 1, NULL, 40, NULL, 26.5, 2700, '10.6:1', 54, 54.5, 'liquid', 'Mikuni 34mm flat-slide carburetor', 'manual', 6, 'chain', 125, NULL, 'Off-road'),
(46, 'kawasaki-kx-250-250-f-2001', '2-stroke', 249, 1, NULL, 58, 9000, 50, 8000, 'dual-stage', 66.4, 72, 'liquid', 'Mikuni 38mm flat-slide carburetor', 'manual', 5, 'chain', 135, NULL, 'Off-road'),
(47, 'kawasaki-kx-250-250-f-2002', '2-stroke', 249, 1, NULL, 58, 9000, 50, 8000, 'dual-stage', 66.4, 72, 'liquid', 'Mikuni 38mm flat-slide carburetor', 'manual', 5, 'chain', 135, NULL, 'Off-road'),
(48, 'kawasaki-kx-250-250-f-2005', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin FCR37 carburetor', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(49, 'kawasaki-kx-250-250-f-2006', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin FCR37 carburetor', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(50, 'kawasaki-kx-250-250-f-2007', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin FCR37 carburetor', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(51, 'kawasaki-kx-250-250-f-2008', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin FCR37 carburetor', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(52, 'kawasaki-kx-250-250-f-2009', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin FCR37 carburetor', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(53, 'kawasaki-kx-250-250-f-2010', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin FCR37 carburetor', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(54, 'kawasaki-kx-250-250-f-2011', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin EFI, 44mm throttle body', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(55, 'kawasaki-kx-250-250-f-2012', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin EFI, 44mm throttle body', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(56, 'kawasaki-kx-250-250-f-2013', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin EFI, 44mm throttle body', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(57, 'kawasaki-kx-250-250-f-2014', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin EFI, 44mm throttle body', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(58, 'kawasaki-kx-250-250-f-2015', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin EFI, 44mm throttle body', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(59, 'kawasaki-kx-250-250-f-2016', '4-stroke', 249, 1, 4, 43, 11500, 30, 9000, '13.8:1', 77, 53.6, 'liquid', 'Keihin EFI, 44mm throttle body', 'manual', 5, 'chain', 145, NULL, 'Off-road'),
(60, 'kawasaki-kx-250-250-f-2021', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(61, 'kawasaki-kx-250-250-f-2022', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(62, 'kawasaki-kx-250-250-f-2023', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(63, 'kawasaki-kx-250-250-f-2024', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(64, 'kawasaki-kx-250-250-f-2025', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(65, 'kawasaki-kx-250-250-f-2026', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(66, 'kawasaki-kx-250-x-2021', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(67, 'kawasaki-kx-250-x-2022', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(68, 'kawasaki-kx-250-x-2023', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(69, 'kawasaki-kx-250-x-2024', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(70, 'kawasaki-kx-250-x-2025', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(71, 'kawasaki-kx-250-x-2026', '4-stroke', 249, 1, 4, NULL, NULL, NULL, NULL, '14.2:1', 78, 52.2, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(72, 'kawasaki-kx-450-f-2006', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(73, 'kawasaki-kx-450-f-2007', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(74, 'kawasaki-kx-450-f-2008', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(75, 'kawasaki-kx-450-f-2009', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(76, 'kawasaki-kx-450-f-2010', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(77, 'kawasaki-kx-450-f-2011', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(78, 'kawasaki-kx-450-f-2012', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(79, 'kawasaki-kx-450-f-2013', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(80, 'kawasaki-kx-450-f-2014', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(81, 'kawasaki-kx-450-f-2015', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(82, 'kawasaki-kx-450-f-2016', '4-stroke', 449, 1, 4, 56, 8500, 50, 7000, '12.8:1', 96, 62.1, 'liquid', 'Keihin EFI, 43-44mm throttle body', 'manual', 5, 'chain', 150, NULL, 'Off-road'),
(83, 'kawasaki-kx-450-f-2019', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(84, 'kawasaki-kx-450-f-2020', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(85, 'kawasaki-kx-450-f-2021', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(86, 'kawasaki-kx-450-f-2022', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(87, 'kawasaki-kx-450-f-2023', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(88, 'kawasaki-kx-450-f-2024', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(89, 'kawasaki-kx-450-f-2025', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(90, 'kawasaki-kx-450-f-2026', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(91, 'kawasaki-kx-450-x-2021', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(92, 'kawasaki-kx-450-x-2022', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(93, 'kawasaki-kx-450-x-2023', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(94, 'kawasaki-kx-450-x-2025', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(95, 'kawasaki-kx-450-x-2026', '4-stroke', 449, 1, 4, NULL, NULL, NULL, NULL, '12.5:1', 96, 62.1, 'liquid', 'Keihin DFI, 44mm throttle body', 'manual', 5, 'chain', NULL, NULL, 'Off-road'),
(96, 'kawasaki-kx-65-2009', '2-stroke', 64, 1, NULL, 12, 12500, 9, 11000, '8.4:1', 44, 42, 'liquid', 'Mikuni VM24SS carburetor', 'manual', 6, 'chain', 95, NULL, 'Off-road'),
(97, 'kawasaki-kx-65-2010', '2-stroke', 64, 1, NULL, 12, 12500, 9, 11000, '8.4:1', 44, 42, 'liquid', 'Mikuni VM24SS carburetor', 'manual', 6, 'chain', 95, NULL, 'Off-road'),
(98, 'kawasaki-kx-65-monster-2009', '2-stroke', 64, 1, NULL, 12, 12500, 9, 11000, '8.4:1', 44, 42, 'liquid', 'Mikuni VM24SS carburetor', 'manual', 6, 'chain', 95, NULL, 'Off-road'),
(99, 'kawasaki-kz-1000-touring-2001', '4-stroke', 998, 4, 2, 90, NULL, NULL, NULL, '8.7:1', 69.4, 66, 'air', 'Mikuni BS34 carburetors (x4)', 'manual', 5, 'shaft', 175, 6.5, 'EPA'),
(100, 'kawasaki-kz-1000-touring-2002', '4-stroke', 998, 4, 2, 90, NULL, NULL, NULL, '8.7:1', 69.4, 66, 'air', 'Mikuni BS34 carburetors (x4)', 'manual', 5, 'shaft', 175, 6.5, 'EPA'),
(101, 'kawasaki-maxi-ii-100cc-1997', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(102, 'kawasaki-maxi-ii-100cc-1998', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(103, 'kawasaki-maxi-ii-100cc-1999', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(104, 'kawasaki-ninja-1000-2011', '4-stroke', 1043, 4, 4, 138, 9600, 110, 7800, '11.8:1', 77, 56, 'liquid', 'Keihin EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 3'),
(105, 'kawasaki-ninja-1000-2012', '4-stroke', 1043, 4, 4, 138, 9600, 110, 7800, '11.8:1', 77, 56, 'liquid', 'Keihin EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 3'),
(106, 'kawasaki-ninja-1000-2013', '4-stroke', 1043, 4, 4, 138, 9600, 110, 7800, '11.8:1', 77, 56, 'liquid', 'Keihin EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 3'),
(107, 'kawasaki-ninja-1000-2014', '4-stroke', 1043, 4, 4, 138, 9600, 110, 7800, '11.8:1', 77, 56, 'liquid', 'Keihin EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 3'),
(108, 'kawasaki-ninja-1000-2017', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Keihin EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 4'),
(109, 'kawasaki-ninja-1000-2018', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Keihin EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 4'),
(110, 'kawasaki-ninja-1000-2020', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Keihin EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 4'),
(111, 'kawasaki-ninja-1000-tourer-2015', '4-stroke', 1043, 4, 4, 138, 9600, 110, 7800, '11.8:1', 77, 56, 'liquid', 'Keihin EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 3'),
(112, 'kawasaki-ninja-1000-tourer-2018', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Keihin EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 4'),
(113, 'kawasaki-ninja-1000-tourer-2020', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Keihin EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 4'),
(114, 'kawasaki-ninja-250r-2008', '4-stroke', 249, 2, 4, 30, 11000, 22, 10000, '11.6:1', 62, 41.2, 'liquid', '2x Keihin 30mm CV carburetors', 'manual', 6, 'chain', 150, 3.8, 'Euro 3'),
(115, 'kawasaki-ninja-250r-2009', '4-stroke', 249, 2, 4, 30, 11000, 22, 10000, '11.6:1', 62, 41.2, 'liquid', '2x Keihin 30mm CV carburetors', 'manual', 6, 'chain', 150, 3.8, 'Euro 3'),
(116, 'kawasaki-ninja-250r-2010', '4-stroke', 249, 2, 4, 30, 11000, 22, 10000, '11.6:1', 62, 41.2, 'liquid', '2x Keihin 30mm CV carburetors', 'manual', 6, 'chain', 150, 3.8, 'Euro 3'),
(117, 'kawasaki-ninja-250r-2011', '4-stroke', 249, 2, 4, 30, 10500, 22, 10000, '11.6:1', 62, 41.2, 'liquid', '2x Keihin 30mm CV carburetors', 'manual', 6, 'chain', 150, 3.8, 'Euro 3'),
(118, 'kawasaki-ninja-250r-2012', '4-stroke', 249, 2, 4, 30, 10500, 22, 10000, '11.6:1', 62, 41.2, 'liquid', '2x Keihin 30mm CV carburetors', 'manual', 6, 'chain', 150, 3.8, 'Euro 3'),
(119, 'kawasaki-ninja-300-2013', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 3'),
(120, 'kawasaki-ninja-300-2014', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 3'),
(121, 'kawasaki-ninja-300-2015', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 3'),
(122, 'kawasaki-ninja-300-2016', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 3'),
(123, 'kawasaki-ninja-300-2017', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 4'),
(124, 'kawasaki-ninja-300-2018', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 4'),
(125, 'kawasaki-ninja-300-2023', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 5'),
(126, 'kawasaki-ninja-300-2024', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 5'),
(127, 'kawasaki-ninja-300-2025', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 5'),
(128, 'kawasaki-ninja-300-2026', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.6, 'Euro 5'),
(129, 'kawasaki-ninja-400-2019', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 4'),
(130, 'kawasaki-ninja-400-2020', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 4'),
(131, 'kawasaki-ninja-400-2021', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 5'),
(132, 'kawasaki-ninja-400-2022', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 5'),
(133, 'kawasaki-ninja-400-2023', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 5'),
(134, 'kawasaki-ninja-400-2024', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 5'),
(135, 'kawasaki-ninja-500-2025', '4-stroke', 451, 2, 4, 51, 10000, 43, 7500, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 180, 3.6, 'Euro 5'),
(136, 'kawasaki-ninja-500-2026', '4-stroke', 451, 2, 4, 51, 10000, 43, 7500, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 180, 3.6, 'Euro 5'),
(137, 'kawasaki-ninja-500-se-2025', '4-stroke', 451, 2, 4, 51, 10000, 43, 7500, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 180, 3.6, 'Euro 5'),
(138, 'kawasaki-ninja-500-se-2026', '4-stroke', 451, 2, 4, 51, 10000, 43, 7500, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 180, 3.6, 'Euro 5'),
(139, 'kawasaki-ninja-650r-649cc-2011', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 72, 8500, 64, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(140, 'kawasaki-ninja-650r-649cc-2012', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 72, 8500, 64, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(141, 'kawasaki-ninja-650r-649cc-2013', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 72, 8500, 64, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(142, 'kawasaki-ninja-650r-649cc-2014', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 72, 8500, 64, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(143, 'kawasaki-ninja-650r-649cc-2016', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 72, 8500, 64, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(144, 'kawasaki-ninja-650r-649cc-2017', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 67, 8000, 65.7, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, dual 36mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(145, 'kawasaki-ninja-650r-649cc-2018', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 67, 8000, 65.7, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, dual 36mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(146, 'kawasaki-ninja-650r-649cc-2020', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 67, 8000, 65.7, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, dual 36mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(147, 'kawasaki-ninja-650r-649cc-2021', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 67, 8000, 65.7, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, dual 36mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(148, 'kawasaki-ninja-650r-649cc-2022', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 67, 8000, 65.7, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, dual 36mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(149, 'kawasaki-ninja-650r-649cc-2024', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 67, 8000, 65.7, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, dual 36mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(150, 'kawasaki-ninja-650r-649cc-2025', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 67, 8000, 65.7, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, dual 36mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(151, 'kawasaki-ninja-650r-649cc-2026', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 67, 8000, 65.7, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, dual 36mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(152, 'kawasaki-ninja-h2-998cc-2016', 'Liquid-cooled, DOHC, 4-valve, in-line four, supercharged', 998, 4, 4, 197, 11000, 133.5, 10000, '8.5:1', 76, 55, 'liquid', 'DFI, supercharged, four 50mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(153, 'kawasaki-ninja-h2-sx-se-998cc-2019', 'Liquid-cooled, DOHC, 4-valve, in-line four, supercharged', 998, 4, 4, 210, 10000, 136.9, 9500, '11.2:1', 76, 55, 'liquid', 'DFI, supercharged, four 40mm throttle bodies, dual injectors', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(154, 'kawasaki-ninja-h2-sx-se-998cc-2020', 'Liquid-cooled, DOHC, 4-valve, in-line four, supercharged', 998, 4, 4, 210, 10000, 136.9, 9500, '11.2:1', 76, 55, 'liquid', 'DFI, supercharged, four 40mm throttle bodies, dual injectors', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(155, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2011', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13000, 114, 11500, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(156, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2012', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13000, 114, 11500, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(157, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2013', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13000, 114, 11500, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(158, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2014', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13000, 114, 11500, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(159, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2015', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13000, 114, 11500, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(160, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2017', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13000, 114, 11600, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(161, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2018', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13000, 114, 11600, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(162, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2019', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13000, 114, 11600, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(163, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2020', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13000, 114, 11600, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(164, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2021', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13200, 114.9, 11400, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(165, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2022', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13200, 114.9, 11400, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(166, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2023', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13200, 114.9, 11400, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(167, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2024', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13200, 114.9, 11400, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(168, 'kawasaki-ninja-zx-10-zx-10r-1000cc-30th-aniv-2025', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13200, 114.9, 11400, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(169, 'kawasaki-ninja-zx-10r-se-1000cc-2019', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 201, 13500, 114.9, 11200, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(170, 'kawasaki-ninja-zx-10r-se-1000cc-2020', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 201, 13500, 114.9, 11200, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(171, 'kawasaki-ninja-zx-10rr-998cc-2018', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 998, 4, 4, 200, 13000, 114, 11500, '13.0:1', 76, 55, 'liquid', 'DFI, four 47mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(172, 'kawasaki-ninja-zx-4r-2024', '4-stroke', 399, 4, 4, 76, 14500, 37.6, 12500, '12.3:1', 57, 39.1, 'liquid', 'DFI, 4x34mm throttle bodies', 'manual', 6, 'chain', 225, 5, 'Euro 5'),
(173, 'kawasaki-ninja-zx-4r-2025', '4-stroke', 399, 4, 4, 76, 14500, 37.6, 12500, '12.3:1', 57, 39.1, 'liquid', 'DFI, 4x34mm throttle bodies', 'manual', 6, 'chain', 225, 5, 'Euro 5'),
(174, 'kawasaki-ninja-zx-4rr-2026', '4-stroke', 399, 4, 4, 76, 14500, 37.6, 12500, '12.3:1', 57, 39.1, 'liquid', 'DFI, 4x34mm throttle bodies', 'manual', 6, 'chain', 225, 5, 'Euro 5'),
(175, 'kawasaki-ninja-zx-6r-600cc-2011', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 599, 4, 4, 128, 14000, 67, 11800, '13.3:1', 67, 42.5, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(176, 'kawasaki-ninja-zx-6r-600cc-2012', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 599, 4, 4, 128, 14000, 67, 11800, '13.3:1', 67, 42.5, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(177, 'kawasaki-ninja-zx-6r-600cc-2013', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 599, 4, 4, 128, 14000, 67, 11800, '13.3:1', 67, 42.5, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(178, 'kawasaki-ninja-zx-6r-636cc-2013', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 128, 13500, 70, 11000, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(179, 'kawasaki-ninja-zx-6r-636cc-2014', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 128, 13500, 70, 11000, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(180, 'kawasaki-ninja-zx-6r-636cc-2015', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 128, 13500, 70, 11000, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(181, 'kawasaki-ninja-zx-6r-636cc-2016', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 128, 13500, 70, 11000, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(182, 'kawasaki-ninja-zx-6r-636cc-2020', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 129, 13500, 70.5, 11000, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(183, 'kawasaki-ninja-zx-6r-636cc-2021', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 127.3, 13500, 70.6, 11500, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(184, 'kawasaki-ninja-zx-6r-636cc-2022', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 127.3, 13500, 70.6, 11500, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(185, 'kawasaki-ninja-zx-6r-636cc-2023', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 127.3, 13500, 70.6, 11500, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(186, 'kawasaki-ninja-zx-6r-636cc-2024', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 127.3, 13500, 70.6, 11500, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(187, 'kawasaki-ninja-zx-6r-636cc-2025', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 127.3, 13500, 70.6, 11500, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(188, 'kawasaki-ninja-zx-6r-636cc-2026', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 636, 4, 4, 127.3, 13500, 70.6, 11500, '12.9:1', 67, 45.1, 'liquid', 'DFI, four 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(189, 'kawasaki-versys-1000-2012', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 3'),
(190, 'kawasaki-versys-1000-2013', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 3'),
(191, 'kawasaki-versys-1000-2015', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 3'),
(192, 'kawasaki-versys-1000-2016', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 3'),
(193, 'kawasaki-versys-1000-2017', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 4'),
(194, 'kawasaki-versys-1000-2018', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 4'),
(195, 'kawasaki-versys-1000-2019', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 4'),
(196, 'kawasaki-versys-1000-2020', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 4'),
(197, 'kawasaki-versys-1000-2021', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 5'),
(198, 'kawasaki-versys-1000-2022', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 5'),
(199, 'kawasaki-versys-1000-2023', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 5'),
(200, 'kawasaki-versys-1000-2024', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 5'),
(201, 'kawasaki-versys-1000-grand-tourer-2013', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 3'),
(202, 'kawasaki-versys-1000-grand-tourer-2015', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 3'),
(203, 'kawasaki-versys-1000-grand-tourer-2016', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 3'),
(204, 'kawasaki-versys-1000-grand-tourer-2017', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 4'),
(205, 'kawasaki-versys-1000-grand-tourer-2018', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 4'),
(206, 'kawasaki-versys-1000-grand-tourer-2019', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 4'),
(207, 'kawasaki-versys-1000-grand-tourer-2020', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 4'),
(208, 'kawasaki-versys-1000-grand-tourer-2021', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 5'),
(209, 'kawasaki-versys-1000-grand-tourer-2022', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 5'),
(210, 'kawasaki-versys-1000-grand-tourer-2023', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 5'),
(211, 'kawasaki-versys-1000-grand-tourer-2024', '4-stroke', 1043, 4, 4, 118, 9000, 102, 7700, '10.3:1', 77, 56, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 225, 6.2, 'Euro 5'),
(212, 'kawasaki-versys-1100-2026', '4-stroke', 1099, 4, 4, 133, NULL, NULL, NULL, NULL, NULL, NULL, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 230, 5.8, 'Euro 5'),
(213, 'kawasaki-versys-1100-grand-tourer-2026', '4-stroke', 1099, 4, 4, 133, NULL, NULL, NULL, NULL, NULL, NULL, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 230, 5.8, 'Euro 5'),
(214, 'kawasaki-versys-650cc-2011', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'DFI, dual 38mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(215, 'kawasaki-versys-650cc-2012', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'DFI, dual 38mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(216, 'kawasaki-versys-650cc-2013', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'DFI, dual 38mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(217, 'kawasaki-versys-650cc-2015', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 69, 8500, 64, 7000, '10.6:1', 83, 60, 'liquid', 'DFI, dual 38mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(218, 'kawasaki-versys-650cc-2016', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 69, 8500, 64, 7000, '10.6:1', 83, 60, 'liquid', 'DFI, dual 38mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(219, 'kawasaki-versys-650cc-2017', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 69, 8500, 64, 7000, '10.6:1', 83, 60, 'liquid', 'DFI, dual 38mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(220, 'kawasaki-versys-650cc-2018', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 69, 8500, 64, 7000, '10.6:1', 83, 60, 'liquid', 'DFI, dual 38mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(221, 'kawasaki-versys-650cc-2019', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 69, 8500, 64, 7000, '10.6:1', 83, 60, 'liquid', 'DFI, dual 38mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(222, 'kawasaki-versys-650cc-2020', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 69, 8500, 64, 7000, '10.6:1', 83, 60, 'liquid', 'DFI, dual 38mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 4'),
(223, 'kawasaki-versys-650cc-2021', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 69, 8500, 64, 7000, '10.6:1', 83, 60, 'liquid', 'DFI, dual 38mm throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(224, 'kawasaki-versys-650cc-2022', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 66, 8500, 61, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(225, 'kawasaki-versys-650cc-2023', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 66, 8500, 61, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(226, 'kawasaki-versys-650cc-2024', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 66, 8500, 61, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(227, 'kawasaki-versys-650cc-2025', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 66, 8500, 61, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(228, 'kawasaki-versys-650cc-2026', 'Liquid-cooled, DOHC, 4-valve, parallel-twin, 4-stroke', 649, 2, 4, 66, 8500, 61, 7000, '10.8:1', 83, 60, 'liquid', 'DFI, dual 38mm Keihin throttle bodies', 'manual', 6, 'chain', NULL, NULL, 'Euro 5'),
(229, 'kawasaki-versys-city-650-2012', '4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.5, 'Euro 3'),
(230, 'kawasaki-versys-tourer-650-2011', '4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.5, 'Euro 3'),
(231, 'kawasaki-versys-tourer-650-2012', '4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.5, 'Euro 3'),
(232, 'kawasaki-versys-tourer-650-2013', '4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.5, 'Euro 3'),
(233, 'kawasaki-versys-tourer-650-2016', '4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.5, 'Euro 3'),
(234, 'kawasaki-versys-tourer-650-2017', '4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.5, 'Euro 4'),
(235, 'kawasaki-versys-tourer-650-2018', '4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.5, 'Euro 4'),
(236, 'kawasaki-versys-tourer-650-2019', '4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.5, 'Euro 4'),
(237, 'kawasaki-versys-tourer-650-2020', '4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.5, 'Euro 4'),
(238, 'kawasaki-versys-tourer-650-2021', '4-stroke', 649, 2, 4, 64, 8000, 61, 6800, '10.6:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.5, 'Euro 5'),
(239, 'kawasaki-versys-tourer-650-2022', '4-stroke', 649, 2, 4, 67, 8500, 61, 7000, '10.8:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(240, 'kawasaki-versys-tourer-650-2023', '4-stroke', 649, 2, 4, 67, 8500, 61, 7000, '10.8:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(241, 'kawasaki-versys-tourer-650-2024', '4-stroke', 649, 2, 4, 67, 8500, 61, 7000, '10.8:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(242, 'kawasaki-versys-tourer-650-2025', '4-stroke', 649, 2, 4, 67, 8500, 61, 7000, '10.8:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(243, 'kawasaki-versys-tourer-650-2026', '4-stroke', 649, 2, 4, 67, 8500, 61, 7000, '10.8:1', 83, 60, 'liquid', 'Digital EFI, 2x38mm Keihin throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(244, 'kawasaki-versys-x-300-2018', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 4'),
(245, 'kawasaki-versys-x-300-2020', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 4'),
(246, 'kawasaki-versys-x-300-2021', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(247, 'kawasaki-versys-x-300-2022', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(248, 'kawasaki-versys-x-300-2023', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(249, 'kawasaki-versys-x-300-2024', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(250, 'kawasaki-versys-x-300-2025', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(251, 'kawasaki-versys-x-300-2026', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(252, 'kawasaki-versys-x-300-tourer-2017', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 4'),
(253, 'kawasaki-versys-x-300-tourer-2018', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 4'),
(254, 'kawasaki-versys-x-300-tourer-2020', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 4'),
(255, 'kawasaki-versys-x-300-tourer-2021', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(256, 'kawasaki-versys-x-300-tourer-2022', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(257, 'kawasaki-versys-x-300-tourer-2023', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(258, 'kawasaki-versys-x-300-tourer-2024', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(259, 'kawasaki-versys-x-300-tourer-2025', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(260, 'kawasaki-versys-x-300-tourer-2026', '4-stroke', 296, 2, 4, 40, 11500, 25.7, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.9, 'Euro 5'),
(261, 'kawasaki-vulcan-800-classic-1997', '4-stroke', 805, 2, 4, 56, 7000, 64, 3300, '9.5:1', 88, 66.2, 'liquid', 'Keihin 36mm CV carburetor', 'manual', 5, 'chain', 160, 5.5, 'EPA'),
(262, 'kawasaki-vulcan-800-classic-1998', '4-stroke', 805, 2, 4, 56, 7000, 64, 3300, '9.5:1', 88, 66.2, 'liquid', 'Keihin 36mm CV carburetor', 'manual', 5, 'chain', 160, 5.5, 'EPA'),
(263, 'kawasaki-vulcan-800-classic-1999', '4-stroke', 805, 2, 4, 56, 7000, 64, 3300, '9.5:1', 88, 66.2, 'liquid', 'Keihin 36mm CV carburetor', 'manual', 5, 'chain', 160, 5.5, 'EPA'),
(264, 'kawasaki-vulcan-800-classic-2000', '4-stroke', 805, 2, 4, 56, 7000, 64, 3300, '9.5:1', 88, 66.2, 'liquid', 'Keihin 36mm CV carburetor', 'manual', 5, 'chain', 160, 5.5, 'EPA'),
(265, 'kawasaki-vulcan-800-classic-2001', '4-stroke', 805, 2, 4, 56, 7000, 64, 3300, '9.5:1', 88, 66.2, 'liquid', 'Keihin 36mm CV carburetor', 'manual', 5, 'chain', 160, 5.5, 'EPA'),
(266, 'kawasaki-vulcan-800-classic-2002', '4-stroke', 805, 2, 4, 56, 7000, 64, 3300, '9.5:1', 88, 66.2, 'liquid', 'Keihin 36mm CV carburetor', 'manual', 5, 'chain', 160, 5.5, 'EPA'),
(267, 'kawasaki-vulcan-800-classic-2003', '4-stroke', 805, 2, 4, 56, 7000, 64, 3300, '9.5:1', 88, 66.2, 'liquid', 'Keihin 36mm CV carburetor', 'manual', 5, 'chain', 160, 5.5, 'EPA'),
(268, 'kawasaki-vulcan-900-classic-lt-2010', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(269, 'kawasaki-vulcan-900-classic-lt-2011', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(270, 'kawasaki-vulcan-900-classic-lt-2012', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(271, 'kawasaki-vulcan-900-classic-lt-2013', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(272, 'kawasaki-vulcan-900-classic-lt-2015', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(273, 'kawasaki-vulcan-900-custom-2010', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(274, 'kawasaki-vulcan-900-custom-2011', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(275, 'kawasaki-vulcan-900-custom-2012', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(276, 'kawasaki-vulcan-900-custom-2013', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(277, 'kawasaki-vulcan-900-custom-2015', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(278, 'kawasaki-vulcan-en-500-ltd-1997', '4-stroke', 498, 2, 4, 46, 8000, 45, 6000, '10.2:1', 74, 58, 'liquid', 'Keihin CVK32 carburetor', 'manual', 6, 'chain', 160, 5, 'EPA'),
(279, 'kawasaki-vulcan-en-500-ltd-1998', '4-stroke', 498, 2, 4, 46, 8000, 45, 6000, '10.2:1', 74, 58, 'liquid', 'Keihin CVK32 carburetor', 'manual', 6, 'chain', 160, 5, 'EPA'),
(280, 'kawasaki-vulcan-s-650-2015', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 3'),
(281, 'kawasaki-vulcan-s-650-2016', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 3'),
(282, 'kawasaki-vulcan-s-650-2017', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 4'),
(283, 'kawasaki-vulcan-s-650-2018', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 4'),
(284, 'kawasaki-vulcan-s-650-2019', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 4'),
(285, 'kawasaki-vulcan-s-650-2020', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 4'),
(286, 'kawasaki-vulcan-s-650-2021', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(287, 'kawasaki-vulcan-s-650-2022', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(288, 'kawasaki-vulcan-s-650-2023', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(289, 'kawasaki-vulcan-s-650-2024', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(290, 'kawasaki-vulcan-s-650-2025', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(291, 'kawasaki-vulcan-s-650-2026', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(292, 'kawasaki-vulcan-s-650-cafe-2018', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 4'),
(293, 'kawasaki-vulcan-s-650-cafe-2019', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 4'),
(294, 'kawasaki-vulcan-s-650-cafe-2020', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 4'),
(295, 'kawasaki-vulcan-s-650-cafe-2021', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(296, 'kawasaki-vulcan-s-650-cafe-2022', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(297, 'kawasaki-vulcan-s-650-cafe-2023', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(298, 'kawasaki-vulcan-s-650-cafe-2025', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(299, 'kawasaki-vulcan-s-650-cafe-2026', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(300, 'kawasaki-vulcan-s-650-special-edition-2017', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 4'),
(301, 'kawasaki-vulcan-s-650-special-edition-2018', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 4'),
(302, 'kawasaki-vulcan-s-650-special-edition-2023', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(303, 'kawasaki-vulcan-s-650-special-edition-2025', '4-stroke', 649, 2, 4, 61, 7500, 63, 6600, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'belt', 175, 4.2, 'Euro 5'),
(304, 'kawasaki-vulcan-vn-1500-classic-mean-streak-1995', '4-stroke', 1470, 2, 4, 64, 4700, 112, 3000, '8.6:1', 102, 90, 'liquid', 'Keihin CVK40 carburetor', 'manual', 5, 'shaft', 170, 6.5, 'EPA'),
(305, 'kawasaki-vulcan-vn-1500-classic-mean-streak-1996', '4-stroke', 1470, 2, 4, 64, 4700, 112, 3000, '8.6:1', 102, 90, 'liquid', 'Keihin CVK40 carburetor', 'manual', 5, 'shaft', 170, 6.5, 'EPA'),
(306, 'kawasaki-vulcan-vn-1500-classic-mean-streak-1997', '4-stroke', 1470, 2, 4, 64, 4700, 112, 3000, '8.6:1', 102, 90, 'liquid', 'Keihin CVK40 carburetor', 'manual', 5, 'shaft', 170, 6.5, 'EPA'),
(307, 'kawasaki-vulcan-vn-1500-classic-mean-streak-1998', '4-stroke', 1470, 2, 4, 64, 4700, 112, 3000, '8.6:1', 102, 90, 'liquid', 'Keihin CVK40 carburetor', 'manual', 5, 'shaft', 170, 6.5, 'EPA'),
(308, 'kawasaki-vulcan-vn-1500-classic-mean-streak-1999', '4-stroke', 1470, 2, 4, 64, 4700, 112, 3000, '8.6:1', 102, 90, 'liquid', 'Keihin CVK40 carburetor', 'manual', 5, 'shaft', 170, 6.5, 'EPA'),
(309, 'kawasaki-vulcan-vn-1500-classic-mean-streak-2000', '4-stroke', 1470, 2, 4, 64, 4700, 112, 3000, '8.6:1', 102, 90, 'liquid', 'Keihin CVK40 carburetor', 'manual', 5, 'shaft', 170, 6.5, 'EPA'),
(310, 'kawasaki-vulcan-vn-1500-classic-mean-streak-2001', '4-stroke', 1470, 2, 4, 64, 4700, 112, 3000, '8.6:1', 102, 90, 'liquid', 'Keihin CVK40 carburetor', 'manual', 5, 'shaft', 170, 6.5, 'EPA'),
(311, 'kawasaki-vulcan-vn-1500-classic-mean-streak-2002', '4-stroke', 1470, 2, 4, 72, 5500, 114, 3000, '9.0:1', 102, 90, 'liquid', 'Mitsubishi digital EFI, dual 40mm throttle bodies', 'manual', 5, 'shaft', 185, 7, 'EPA'),
(312, 'kawasaki-vulcan-vn-1500-classic-mean-streak-2003', '4-stroke', 1470, 2, 4, 72, 5500, 114, 3000, '9.0:1', 102, 90, 'liquid', 'Mitsubishi digital EFI, dual 40mm throttle bodies', 'manual', 5, 'shaft', 185, 7, 'EPA'),
(313, 'kawasaki-vulcan-vn-1500-classic-mean-streak-2004', '4-stroke', 1470, 2, 4, 72, 5500, 114, 3000, '9.0:1', 102, 90, 'liquid', 'Mitsubishi digital EFI, dual 40mm throttle bodies', 'manual', 5, 'shaft', 185, 7, 'EPA'),
(314, 'kawasaki-vulcan-vn-1500-classic-mean-streak-2005', '4-stroke', 1470, 2, 4, 72, 5500, 114, 3000, '9.0:1', 102, 90, 'liquid', 'Mitsubishi digital EFI, dual 40mm throttle bodies', 'manual', 5, 'shaft', 185, 7, 'EPA'),
(315, 'kawasaki-vulcan-vn-1600-mean-streak-2005', '4-stroke', 1552, 2, 4, 73, 5500, 126, 2500, '9.5:1', 102, 95, 'liquid', 'Digital EFI, dual throttle bodies', 'manual', 5, 'belt', 175, 6.8, 'EPA'),
(316, 'kawasaki-vulcan-vn-1600-mean-streak-2006', '4-stroke', 1552, 2, 4, 73, 5500, 126, 2500, '9.5:1', 102, 95, 'liquid', 'Digital EFI, dual throttle bodies', 'manual', 5, 'belt', 175, 6.8, 'EPA'),
(317, 'kawasaki-vulcan-vn-2000-2005', '4-stroke', 2053, 2, 4, 103, 4800, 191, 3000, '9.5:1', 103, 123.2, 'liquid', 'Digital EFI', 'manual', 5, 'belt', 170, 7.5, 'EPA'),
(318, 'kawasaki-vulcan-vn-2000-2006', '4-stroke', 2053, 2, 4, 103, 4800, 191, 3000, '9.5:1', 103, 123.2, 'liquid', 'Digital EFI', 'manual', 5, 'belt', 170, 7.5, 'EPA'),
(319, 'kawasaki-vulcan-vn-900-classic-2007', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(320, 'kawasaki-vulcan-vn-900-classic-2008', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(321, 'kawasaki-vulcan-vn-900-classic-2009', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(322, 'kawasaki-vulcan-vn-900-classic-2010', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(323, 'kawasaki-vulcan-vn-900-classic-2011', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(324, 'kawasaki-vulcan-vn-900-classic-2012', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(325, 'kawasaki-vulcan-vn-900-classic-2013', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(326, 'kawasaki-vulcan-vn-900-classic-2015', '4-stroke', 903, 2, 4, 50, 5700, 79, 3700, '9.5:1', 88, 74.2, 'liquid', 'DFI, dual 34mm throttle bodies', 'manual', 5, 'belt', 160, 5.3, 'Euro 3'),
(327, 'kawasaki-z-1000-2004', '4-stroke', 953, 4, 4, 127, 10000, 96, 8000, '11.2:1', 77.2, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 250, 6.5, 'Euro 2'),
(328, 'kawasaki-z-1000-2005', '4-stroke', 953, 4, 4, 127, 10000, 96, 8000, '11.2:1', 77.2, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 250, 6.5, 'Euro 2'),
(329, 'kawasaki-z-1000-2006', '4-stroke', 953, 4, 4, 127, 10000, 96, 8000, '11.2:1', 77.2, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 250, 6.5, 'Euro 3'),
(330, 'kawasaki-z-1000-2008', '4-stroke', 953, 4, 4, 127, 10000, 96, 8000, '11.2:1', 77.2, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 250, 6.5, 'Euro 3'),
(331, 'kawasaki-z-1000-2010', '4-stroke', 1043, 4, 4, 140, 11000, 111, 7300, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6.3, 'Euro 3'),
(332, 'kawasaki-z-1000-2011', '4-stroke', 1043, 4, 4, 140, 11000, 111, 7300, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6.3, 'Euro 3'),
(333, 'kawasaki-z-1000-2012', '4-stroke', 1043, 4, 4, 140, 11000, 111, 7300, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6.3, 'Euro 3'),
(334, 'kawasaki-z-1000-2013', '4-stroke', 1043, 4, 4, 140, 11000, 111, 7300, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6.3, 'Euro 3'),
(335, 'kawasaki-z-1000-2015', '4-stroke', 1043, 4, 4, 140, 11000, 111, 7300, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6.3, 'Euro 3'),
(336, 'kawasaki-z-1000-2016', '4-stroke', 1043, 4, 4, 140, 11000, 111, 7300, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6.3, 'Euro 3'),
(337, 'kawasaki-z-1000-2017', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 4'),
(338, 'kawasaki-z-1000-2018', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 4'),
(339, 'kawasaki-z-1000-2020', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 4'),
(340, 'kawasaki-z-1000-2021', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 5'),
(341, 'kawasaki-z-1000-2022', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 5'),
(342, 'kawasaki-z-1000-2023', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 5'),
(343, 'kawasaki-z-1000-2024', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 5'),
(344, 'kawasaki-z-1000-2025', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 5'),
(345, 'kawasaki-z-1000-h2-2025', '4-stroke (supercharged)', 998, 4, 4, 200, 10500, 137, 8500, '8.3:1', 76, 55, 'liquid', 'DFI with centrifugal supercharger, 4x50mm throttle bodies', 'manual', 6, 'chain', 240, 6.8, 'Euro 5'),
(346, 'kawasaki-z-1000-h2-2026', '4-stroke (supercharged)', 998, 4, 4, 200, 10500, 137, 8500, '8.3:1', 76, 55, 'liquid', 'DFI with centrifugal supercharger, 4x50mm throttle bodies', 'manual', 6, 'chain', 240, 6.8, 'Euro 5'),
(347, 'kawasaki-z-1000-r-edition-2018', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 4'),
(348, 'kawasaki-z-1000-r-edition-2020', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 4'),
(349, 'kawasaki-z-1000-r-edition-2021', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 5'),
(350, 'kawasaki-z-1000-r-edition-2022', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 5'),
(351, 'kawasaki-z-1000-r-edition-2023', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 5'),
(352, 'kawasaki-z-1000-r-edition-2024', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 5'),
(353, 'kawasaki-z-1000-r-edition-2025', '4-stroke', 1043, 4, 4, 142, 10000, 111, 8000, '11.8:1', 77, 56, 'liquid', 'Digital EFI, 38mm throttle bodies', 'manual', 6, 'chain', 250, 6, 'Euro 5'),
(354, 'kawasaki-z-1100-2027', '4-stroke', 1099, 4, 4, 134, 9000, 113, 7600, NULL, NULL, NULL, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 240, 5.9, 'Euro 5'),
(355, 'kawasaki-z-1100-se-2027', '4-stroke', 1099, 4, 4, 134, 9000, 113, 7600, NULL, NULL, NULL, 'liquid', 'Keihin EFI, 4x38mm throttle bodies', 'manual', 6, 'chain', 240, 5.9, 'Euro 5'),
(356, 'kawasaki-z-300-2015', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.7, 'Euro 3'),
(357, 'kawasaki-z-300-2016', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.7, 'Euro 3'),
(358, 'kawasaki-z-300-2018', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.7, 'Euro 4'),
(359, 'kawasaki-z-300-2019', '4-stroke', 296, 2, 4, 39, 11000, 27, 10000, '10.6:1', 62, 49, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 170, 3.7, 'Euro 4'),
(360, 'kawasaki-z-400-2019', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 4'),
(361, 'kawasaki-z-400-2020', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 4'),
(362, 'kawasaki-z-400-2021', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 5'),
(363, 'kawasaki-z-400-2022', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 5'),
(364, 'kawasaki-z-400-2023', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 5'),
(365, 'kawasaki-z-400-2024', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 5'),
(366, 'kawasaki-z-400-se-2023', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 5'),
(367, 'kawasaki-z-400-se-2024', '4-stroke', 399, 2, 4, 49, 10000, 38, 8000, '11.5:1', 70, 51.8, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 175, 3.5, 'Euro 5'),
(368, 'kawasaki-z-500-2025', '4-stroke', 451, 2, 4, 51, 10000, 43, 7500, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 180, 3.6, 'Euro 5'),
(369, 'kawasaki-z-500-2026', '4-stroke', 451, 2, 4, 51, 10000, 43, 7500, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 180, 3.6, 'Euro 5'),
(370, 'kawasaki-z-500-se-2025', '4-stroke', 451, 2, 4, 51, 10000, 43, 7500, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 180, 3.6, 'Euro 5'),
(371, 'kawasaki-z-500-se-2026', '4-stroke', 451, 2, 4, 51, 10000, 43, 7500, '11.3:1', 70, 58.6, 'liquid', 'DFI, 2x32mm throttle bodies', 'manual', 6, 'chain', 180, 3.6, 'Euro 5'),
(372, 'kawasaki-z-650-2018', '4-stroke', 649, 2, 4, 67, 8000, 66, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 4'),
(373, 'kawasaki-z-650-2020', '4-stroke', 649, 2, 4, 67, 8000, 66, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 4'),
(374, 'kawasaki-z-650-2021', '4-stroke', 649, 2, 4, 67, 8000, 66, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(375, 'kawasaki-z-650-2024', '4-stroke', 649, 2, 4, 67, 8000, 66, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(376, 'kawasaki-z-650-2025', '4-stroke', 649, 2, 4, 67, 8000, 66, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(377, 'kawasaki-z-650-2026', '4-stroke', 649, 2, 4, 67, 8000, 66, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(378, 'kawasaki-z-650-rs-2023', '4-stroke', 649, 2, 4, 67, 8000, 66, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'chain', 195, 4.3, 'Euro 5'),
(379, 'kawasaki-z-650-rs-2025', '4-stroke', 649, 2, 4, 67, 8000, 66, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'chain', 195, 4.3, 'Euro 5'),
(380, 'kawasaki-z-650-se-abs-2021', '4-stroke', 649, 2, 4, 67, 8000, 66, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(381, 'kawasaki-z-650-se-abs-2022', '4-stroke', 649, 2, 4, 67, 8000, 66, 6500, '10.8:1', 83, 60, 'liquid', 'DFI, 2x38mm throttle bodies', 'manual', 6, 'chain', 200, 4.3, 'Euro 5'),
(382, 'kawasaki-z-750-2008', '4-stroke', 748, 4, 4, 104, 10500, 78, 8300, '11.3:1', 68.4, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 225, 5.8, 'Euro 3'),
(383, 'kawasaki-z-750-2009', '4-stroke', 748, 4, 4, 104, 10500, 78, 8300, '11.3:1', 68.4, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 225, 5.8, 'Euro 3'),
(384, 'kawasaki-z-750-2010', '4-stroke', 748, 4, 4, 104, 10500, 78, 8300, '11.3:1', 68.4, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 225, 5.8, 'Euro 3'),
(385, 'kawasaki-z-750-2011', '4-stroke', 748, 4, 4, 104, 10500, 78, 8300, '11.3:1', 68.4, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 225, 5.8, 'Euro 3'),
(386, 'kawasaki-z-750-2012', '4-stroke', 748, 4, 4, 104, 10500, 78, 8300, '11.3:1', 68.4, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 225, 5.8, 'Euro 3'),
(387, 'kawasaki-z-800-2013', '4-stroke', 806, 4, 4, 113, 10200, 83, 8000, '11.9:1', 71, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 225, 5.9, 'Euro 3'),
(388, 'kawasaki-z-800-2014', '4-stroke', 806, 4, 4, 113, 10200, 83, 8000, '11.9:1', 71, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 225, 5.9, 'Euro 3'),
(389, 'kawasaki-z-800-2016', '4-stroke', 806, 4, 4, 113, 10200, 83, 8000, '11.9:1', 71, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 225, 5.9, 'Euro 3'),
(390, 'kawasaki-z-800-2017', '4-stroke', 806, 4, 4, 113, 10200, 83, 8000, '11.9:1', 71, 50.9, 'liquid', 'Digital EFI', 'manual', 6, 'chain', 225, 5.9, 'Euro 4'),
(391, 'kawasaki-z-900-2018', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 4'),
(392, 'kawasaki-z-900-2019', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 4'),
(393, 'kawasaki-z-900-2020', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 4'),
(394, 'kawasaki-z-900-2021', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(395, 'kawasaki-z-900-2022', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(396, 'kawasaki-z-900-2023', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(397, 'kawasaki-z-900-2025', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(398, 'kawasaki-z-900-2026', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(399, 'kawasaki-z-900-50th-anniversary-2022', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(400, 'kawasaki-z-900-r-edition-2022', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(401, 'kawasaki-z-900-r-edition-2023', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(402, 'kawasaki-z-900-r-edition-2025', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(403, 'kawasaki-z-900-r-edition-2026', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(404, 'kawasaki-z-900-rs-2019', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 4'),
(405, 'kawasaki-z-900-rs-2020', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 4'),
(406, 'kawasaki-z-900-rs-2022', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 5'),
(407, 'kawasaki-z-900-rs-2023', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 5'),
(408, 'kawasaki-z-900-rs-2024', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 5'),
(409, 'kawasaki-z-900-rs-cafe-2019', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 4'),
(410, 'kawasaki-z-900-rs-cafe-2020', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 4'),
(411, 'kawasaki-z-900-rs-cafe-2023', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 5'),
(412, 'kawasaki-z-900-rs-cafe-2024', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 5'),
(413, 'kawasaki-z-900-rs-cafe-2025', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 5'),
(414, 'kawasaki-z-900-rs-r-edition-2022', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 5'),
(415, 'kawasaki-z-900-rs-r-edition-2023', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 5'),
(416, 'kawasaki-z-900-rs-r-edition-2024', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 5'),
(417, 'kawasaki-z-900-rs-r-edition-2025', '4-stroke', 948, 4, 4, 111, 8500, 98, 6500, '10.8:1', 73.4, 56, 'liquid', 'Keihin EFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 210, 5.5, 'Euro 5'),
(418, 'kawasaki-z-900-se-2021', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(419, 'kawasaki-z-900-se-2026', '4-stroke', 948, 4, 4, 125, 9500, 98.6, 7700, '11.8:1', 73.4, 56, 'liquid', 'DFI, 4x36mm throttle bodies', 'manual', 6, 'chain', 235, 5.6, 'Euro 5'),
(420, 'kawasaki-zx-14-zx-14r-1352cc-2011', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 1352, 4, 4, 194, 9500, 153, 7500, '12.0:1', 84, 61, 'liquid', 'DFI, four 44mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(421, 'kawasaki-zx-14-zx-14r-1352cc-2013', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 1352, 4, 4, 194, 9500, 153, 7500, '12.0:1', 84, 61, 'liquid', 'DFI, four 44mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(422, 'kawasaki-zx-14-zx-14r-1352cc-2014', 'Liquid-cooled, DOHC, 4-valve, in-line four, 4-stroke', 1352, 4, 4, 194, 9500, 153, 7500, '12.0:1', 84, 61, 'liquid', 'DFI, four 44mm throttle bodies, oval sub-throttles', 'manual', 6, 'chain', NULL, NULL, 'Euro 3'),
(423, 'kawasaki-zzr-1200-2004', '4-stroke', 1164, 4, 4, 160, 9800, 125, NULL, '11.0:1', 79, 59.4, 'liquid', 'Keihin EFI', 'manual', 6, 'chain', 280, 7, 'Euro 2'),
(424, 'kawasaki-zzr-1200-2005', '4-stroke', 1164, 4, 4, 160, 9800, 125, NULL, '11.0:1', 79, 59.4, 'liquid', 'Keihin EFI', 'manual', 6, 'chain', 280, 7, 'Euro 2');

-- Join on slug. The FIPE seed derives the same slug from the same descriptor, so this is an
-- equality join rather than a fuzzy name match.
UPDATE tmp_kawasaki_engine_research s
SET motorcycle_id = m.id,
    engine_id     = m.engine_specification_id
FROM motorcycles m
WHERE m.slug = s.slug;

DO $$
BEGIN
    IF pg_get_serial_sequence('engine_specifications', 'id') IS NULL THEN
        RAISE EXCEPTION 'engine_specifications has no serial/identity sequence';
    END IF;
END $$;

-- A catalogue row seeded from FIPE may carry no engine block at all. Give those one before the
-- gap-fill runs, or their figures would be dropped on the floor.
UPDATE tmp_kawasaki_engine_research
SET engine_id = nextval(pg_get_serial_sequence('engine_specifications', 'id')::regclass)
WHERE motorcycle_id IS NOT NULL AND engine_id IS NULL;

INSERT INTO engine_specifications (id)
SELECT s.engine_id
FROM tmp_kawasaki_engine_research s
WHERE s.engine_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM engine_specifications e WHERE e.id = s.engine_id)
ORDER BY s.row_no;

UPDATE motorcycles m
SET engine_specification_id = s.engine_id
FROM tmp_kawasaki_engine_research s
WHERE m.id = s.motorcycle_id AND m.engine_specification_id IS NULL;

-- COALESCE in every column: whatever the catalogue already holds wins, so this is a gap-fill and
-- re-running the seed changes nothing the second time.
UPDATE engine_specifications e
SET engine_type              = COALESCE(e.engine_type, s.engine_type),
    displacement_cc          = COALESCE(e.displacement_cc, s.displacement_cc),
    cylinders                = COALESCE(e.cylinders, s.cylinders),
    valves_per_cylinder      = COALESCE(e.valves_per_cylinder, s.valves_per_cylinder),
    max_power_hp             = COALESCE(e.max_power_hp, s.max_power_hp),
    max_power_rpm            = COALESCE(e.max_power_rpm, s.max_power_rpm),
    max_torque_nm            = COALESCE(e.max_torque_nm, s.max_torque_nm),
    max_torque_rpm           = COALESCE(e.max_torque_rpm, s.max_torque_rpm),
    compression_ratio        = COALESCE(e.compression_ratio, s.compression_ratio),
    bore_mm                  = COALESCE(e.bore_mm, s.bore_mm),
    stroke_mm                = COALESCE(e.stroke_mm, s.stroke_mm),
    cooling_system           = COALESCE(e.cooling_system, s.cooling_system),
    fuel_system              = COALESCE(e.fuel_system, s.fuel_system),
    transmission_type        = COALESCE(e.transmission_type, s.transmission_type),
    gears                    = COALESCE(e.gears, s.gears),
    final_drive              = COALESCE(e.final_drive, s.final_drive),
    top_speed_kph            = COALESCE(e.top_speed_kph, s.top_speed_kph),
    fuel_consumption_l_100km = COALESCE(e.fuel_consumption_l_100km, s.fuel_consumption_l_100km),
    emission_standard        = COALESCE(e.emission_standard, s.emission_standard)
FROM tmp_kawasaki_engine_research s
WHERE e.id = s.engine_id;

-- The one place this file overrules a value the catalogue already held, and it is allowed to only
-- because the row convicts itself. bore, stroke, cylinders and displacement have one algebraic
-- relation, so a stored pair that misses its own displacement by more than 2% is arithmetically
-- wrong whatever its provenance - and an imported pair that lands within 2% is arithmetically
-- right. Where those two conditions hold at once, the imported pair replaces the stored one.
--
-- The ZZR 1200 is why this exists. The scraped seed publishes 78.0 x 59.0 mm against its own
-- 1164 cc, which computes to 1128 cc; the figures are 79.0 x 59.4 mm, rounded to whole millimetres
-- by the source until the error compounded past 3%. Nothing is hardcoded here: no slug is named,
-- the rule tests the arithmetic, and a re-run on corrected upstream data simply matches nothing.
UPDATE engine_specifications e
SET bore_mm   = s.bore_mm,
    stroke_mm = s.stroke_mm
FROM tmp_kawasaki_engine_research s
WHERE e.id = s.engine_id
  AND s.bore_mm IS NOT NULL AND s.stroke_mm IS NOT NULL
  AND e.cylinders IS NOT NULL AND e.displacement_cc IS NOT NULL
  AND e.bore_mm IS NOT NULL AND e.stroke_mm IS NOT NULL
  -- what is stored contradicts the displacement stored beside it
  AND abs(pi() / 4 * e.bore_mm * e.bore_mm * e.stroke_mm * e.cylinders / 1000.0 - e.displacement_cc)
      > 0.02 * e.displacement_cc
  -- and what this import carries does not
  AND abs(pi() / 4 * s.bore_mm * s.bore_mm * s.stroke_mm * e.cylinders / 1000.0 - e.displacement_cc)
      <= 0.02 * e.displacement_cc;

-- ---------------------------------------------------------------------------
-- Post-conditions. Each one fails the migration rather than leaving the catalogue in a state the
-- API would serve as fact.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    bad INTEGER;
    unmatched INTEGER;
    offenders TEXT;
BEGIN
    SELECT count(*) INTO unmatched FROM tmp_kawasaki_engine_research WHERE motorcycle_id IS NULL;
    IF unmatched <> 0 THEN
        -- Not fatal: this seed creates no motorcycles, so an unmatched slug means the catalogue
        -- moved under it. Worth saying out loud, because the row's figures went nowhere.
        RAISE NOTICE 'Kawasaki engine research: % of % slugs are not in the catalogue and were skipped',
            unmatched, (SELECT count(*) FROM tmp_kawasaki_engine_research);
    END IF;

    -- Every matched row must now have an engine block; a row that does not means the link above
    -- failed and the figures were written to an engine nothing points at.
    SELECT count(*) INTO bad
    FROM tmp_kawasaki_engine_research s
    JOIN motorcycles m ON m.id = s.motorcycle_id
    WHERE m.engine_specification_id IS NULL;
    IF bad <> 0 THEN
        RAISE EXCEPTION 'Kawasaki engine research: % matched rows still have no engine block', bad;
    END IF;

    -- The geometry relation is checked again here, against what is actually in the table rather
    -- than against what this file tried to write. That distinction matters: every column above is a
    -- COALESCE, so the stored quartet can be a mixture - a displacement the catalogue already had
    -- beside a bore and stroke this file supplied. Neither source is wrong on its own and both pass
    -- their own checks; only the merged row is impossible. This is the only place that can catch it.
    -- The message names the rows, because a bare count sends the next reader back to the database.
    SELECT count(*), string_agg(slug, ', ' ORDER BY slug) INTO bad, offenders
    FROM (
        SELECT m.slug
        FROM engine_specifications e
        JOIN motorcycles m ON m.engine_specification_id = e.id
        JOIN tmp_kawasaki_engine_research s ON s.motorcycle_id = m.id
        WHERE e.bore_mm IS NOT NULL AND e.stroke_mm IS NOT NULL
          AND e.cylinders IS NOT NULL AND e.displacement_cc IS NOT NULL
          AND abs(pi() / 4 * e.bore_mm * e.bore_mm * e.stroke_mm * e.cylinders / 1000.0 - e.displacement_cc)
              > 0.02 * e.displacement_cc
    ) q;
    IF bad <> 0 THEN
        RAISE EXCEPTION 'Kawasaki engine research: % engine rows have bore/stroke that contradict displacement: %',
            bad, offenders;
    END IF;

    SELECT count(*) INTO bad
    FROM engine_specifications e
    JOIN motorcycles m ON m.engine_specification_id = e.id
    JOIN tmp_kawasaki_engine_research s ON s.motorcycle_id = m.id
    WHERE e.max_power_rpm IS NOT NULL AND e.max_torque_rpm IS NOT NULL
      AND e.max_torque_rpm > e.max_power_rpm;
    IF bad <> 0 THEN
        RAISE EXCEPTION 'Kawasaki engine research: % engine rows peak torque above peak power', bad;
    END IF;
END $$;

COMMIT;
