-- Baseline schema for the motorcycle catalogue. Greenfield: nothing is deployed yet,
-- so one migration replaces ddl-auto instead of a chain of ALTERs against a fiction.
--
-- Identity columns are GENERATED BY DEFAULT (not ALWAYS) because the dev seed inserts
-- explicit ids and then restarts the sequence; ALWAYS would reject those inserts.
--
-- Specification columns are nullable by design: a figure the manufacturer never
-- published must render as a dash, never as a zero.
--
-- Under SQL three-valued logic a CHECK passes when its column is NULL, so every bound
-- below is null-tolerant without an explicit IS NULL branch.

CREATE TABLE engine_specifications (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    engine_type              VARCHAR(80),
    displacement_cc          INTEGER,
    cylinders                INTEGER,
    valves_per_cylinder      INTEGER,
    max_power_hp             NUMERIC(6, 1),
    max_power_rpm            INTEGER,
    max_torque_nm            NUMERIC(6, 1),
    max_torque_rpm           INTEGER,
    compression_ratio        VARCHAR(20),
    bore_mm                  NUMERIC(6, 2),
    stroke_mm                NUMERIC(6, 2),
    cooling_system           VARCHAR(40),
    fuel_system              VARCHAR(120),
    transmission_type        VARCHAR(60),
    gears                    INTEGER,
    final_drive              VARCHAR(40),
    top_speed_kph            INTEGER,
    fuel_consumption_l_100km NUMERIC(5, 2),
    emission_standard        VARCHAR(30),
    CONSTRAINT pk_engine_specifications PRIMARY KEY (id),
    -- Bounds mirror the request DTO exactly (@Positive on counts, @DecimalMin("0.0")
    -- on measurements) so a payload the API accepts can never fail at the database.
    CONSTRAINT ck_engine_specifications_displacement_cc CHECK (displacement_cc > 0),
    CONSTRAINT ck_engine_specifications_cylinders CHECK (cylinders > 0),
    CONSTRAINT ck_engine_specifications_valves_per_cylinder CHECK (valves_per_cylinder > 0),
    CONSTRAINT ck_engine_specifications_max_power_hp CHECK (max_power_hp >= 0),
    CONSTRAINT ck_engine_specifications_max_power_rpm CHECK (max_power_rpm > 0),
    CONSTRAINT ck_engine_specifications_max_torque_nm CHECK (max_torque_nm >= 0),
    CONSTRAINT ck_engine_specifications_max_torque_rpm CHECK (max_torque_rpm > 0),
    CONSTRAINT ck_engine_specifications_bore_mm CHECK (bore_mm >= 0),
    CONSTRAINT ck_engine_specifications_stroke_mm CHECK (stroke_mm >= 0),
    CONSTRAINT ck_engine_specifications_gears CHECK (gears > 0),
    CONSTRAINT ck_engine_specifications_top_speed_kph CHECK (top_speed_kph > 0),
    CONSTRAINT ck_engine_specifications_fuel_consumption CHECK (fuel_consumption_l_100km >= 0)
);

COMMENT ON TABLE engine_specifications IS 'Powertrain block, one row per motorcycle; split out because a catalogue listing rarely loads it.';

CREATE TABLE dimensions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    length_mm           INTEGER,
    width_mm            INTEGER,
    height_mm           INTEGER,
    wheelbase_mm        INTEGER,
    seat_height_mm      INTEGER,
    ground_clearance_mm INTEGER,
    kerb_weight_kg      NUMERIC(6, 1),
    dry_weight_kg       NUMERIC(6, 1),
    fuel_capacity_l     NUMERIC(5, 1),
    payload_kg          NUMERIC(6, 1),
    CONSTRAINT pk_dimensions PRIMARY KEY (id),
    CONSTRAINT ck_dimensions_length_mm CHECK (length_mm > 0),
    CONSTRAINT ck_dimensions_width_mm CHECK (width_mm > 0),
    CONSTRAINT ck_dimensions_height_mm CHECK (height_mm > 0),
    CONSTRAINT ck_dimensions_wheelbase_mm CHECK (wheelbase_mm > 0),
    CONSTRAINT ck_dimensions_seat_height_mm CHECK (seat_height_mm > 0),
    CONSTRAINT ck_dimensions_ground_clearance_mm CHECK (ground_clearance_mm > 0),
    CONSTRAINT ck_dimensions_kerb_weight_kg CHECK (kerb_weight_kg >= 0),
    CONSTRAINT ck_dimensions_dry_weight_kg CHECK (dry_weight_kg >= 0),
    CONSTRAINT ck_dimensions_fuel_capacity_l CHECK (fuel_capacity_l >= 0),
    CONSTRAINT ck_dimensions_payload_kg CHECK (payload_kg >= 0),
    -- Dry weight excludes fluids, so it cannot exceed kerb weight; this catches a
    -- swapped pair at import time and passes whenever either figure is unpublished.
    CONSTRAINT ck_dimensions_dry_weight_below_kerb CHECK (dry_weight_kg <= kerb_weight_kg)
);

COMMENT ON TABLE dimensions IS 'Physical envelope, mass and capacities; every figure optional because manufacturers publish different subsets.';

CREATE TABLE motorcycles (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slug                    VARCHAR(160) NOT NULL,
    brand                   VARCHAR(60) NOT NULL,
    model                   VARCHAR(120) NOT NULL,
    model_year              INTEGER NOT NULL,
    category                VARCHAR(20) NOT NULL,
    price_eur               NUMERIC(10, 2),
    image_url               VARCHAR(512),
    description             VARCHAR(2000),
    frame_type              VARCHAR(120),
    front_suspension        VARCHAR(160),
    rear_suspension         VARCHAR(160),
    front_brake             VARCHAR(160),
    rear_brake              VARCHAR(160),
    abs_type                VARCHAR(80),
    front_tyre              VARCHAR(60),
    rear_tyre               VARCHAR(60),
    engine_specification_id BIGINT,
    dimension_id            BIGINT,
    -- Hibernate maps Instant to TIMESTAMP_UTC, which this dialect renders as
    -- timestamptz; a plain TIMESTAMP here would fail ddl-auto: validate.
    created_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_motorcycles PRIMARY KEY (id),
    CONSTRAINT uk_motorcycles_slug UNIQUE (slug),
    -- @OneToOne means one spec block per motorcycle. Without these, a second motorcycle
    -- could adopt the same row and orphanRemoval would then delete it underneath.
    CONSTRAINT uk_motorcycles_engine UNIQUE (engine_specification_id),
    CONSTRAINT uk_motorcycles_dimension UNIQUE (dimension_id),
    -- Same bounds as @Min(1885)/@Max(2100) on the request DTO; the upper bound is a
    -- literal because a CHECK expression has to be immutable.
    CONSTRAINT ck_motorcycles_model_year CHECK (model_year BETWEEN 1885 AND 2100),
    CONSTRAINT ck_motorcycles_price_eur CHECK (price_eur >= 0),
    -- Category is persisted as EnumType.STRING, so the database is the last line of
    -- defence against a value the Java enum cannot read back.
    CONSTRAINT ck_motorcycles_category CHECK (category IN ('SPORT', 'NAKED', 'TOURING', 'ADVENTURE', 'CRUISER', 'SCOOTER', 'OFF_ROAD', 'SUPERMOTO', 'ELECTRIC')),
    -- NOT NULL still lets an empty or whitespace-only string through a raw INSERT.
    CONSTRAINT ck_motorcycles_brand_not_blank CHECK (btrim(brand) <> ''),
    CONSTRAINT ck_motorcycles_model_not_blank CHECK (btrim(model) <> ''),
    -- The slug is a public URL segment derived by MotorcycleService.slugify; pinning its
    -- shape here stops any other write path publishing a link that breaks routing.
    CONSTRAINT ck_motorcycles_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT fk_motorcycles_engine FOREIGN KEY (engine_specification_id) REFERENCES engine_specifications (id),
    CONSTRAINT fk_motorcycles_dimension FOREIGN KEY (dimension_id) REFERENCES dimensions (id)
);

COMMENT ON TABLE motorcycles IS 'Catalogue aggregate root; slug is the stable public identifier the frontend links to.';

CREATE TABLE motorcycle_additional_specs (
    motorcycle_id BIGINT NOT NULL,
    spec_key      VARCHAR(80) NOT NULL,
    spec_value    VARCHAR(500),
    -- Composite PK is what Hibernate expects for a Map @ElementCollection, and its
    -- leading column doubles as the index the cascading delete needs.
    CONSTRAINT pk_motorcycle_additional_specs PRIMARY KEY (motorcycle_id, spec_key),
    CONSTRAINT ck_additional_specs_key_not_blank CHECK (btrim(spec_key) <> ''),
    -- ON DELETE CASCADE is a net for raw SQL only: Hibernate deletes the children itself.
    CONSTRAINT fk_additional_specs_motorcycle FOREIGN KEY (motorcycle_id) REFERENCES motorcycles (id) ON DELETE CASCADE
);

COMMENT ON TABLE motorcycle_additional_specs IS 'Long-tail key/value specs; a value that becomes a comparison criterion gets promoted to a typed column.';

-- Indexes. The three declared on @Table keep their existing names so the entity and the
-- schema go on describing the same database.

-- Serves SELECT DISTINCT brand ORDER BY brand for the filter sidebar, and brand-sorted paging.
CREATE INDEX idx_motorcycles_brand ON motorcycles (brand);

-- The catalogue filter is lower(brand) = ?, which a plain brand index cannot answer.
CREATE INDEX idx_motorcycles_brand_lower ON motorcycles (lower(brand));

CREATE INDEX idx_motorcycles_category ON motorcycles (category);

CREATE INDEX idx_motorcycles_model_year ON motorcycles (model_year);

-- "Browse a segment, cheapest first" is the most common filter plus sort combination;
-- default ASC ordering also puts the unpriced bikes last, where the catalogue wants them.
CREATE INDEX idx_motorcycles_category_price_eur ON motorcycles (category, price_eur);
